apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: man-nginx-2
  name: man-nginx-2
  namespace: surachai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: man-nginx-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: man-nginx-2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
