apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeops-ng-deploy
  namespace: default
  labels:
    app: kubeops-ng-deploy
spec:
  selector:
    matchLabels:
      app: kubeops-ng-deploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubeops-ng-deploy
    spec:
      containers:
        - name: kubeops-ng-deploy
          image: kubesuperops.azurecr.io/kubesuperops/kubeops-ng-app:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 80
